### ISSUE TITLE
How to save/add more than one Sticker to favorites?

### ISSUE THREAD

**Issue by vartotojas500** [CreativeBuilds/creative-bot#65]
How to save/add more than one Sticker to favorites?

**Comment by Ash-Bash** [comment]
Currently you cant select multiple stickers and save to the Applications Favorites list, yes you can ofcause save more than one to the list just all at once at the sametime. thats if I got what your say right.

**Comment by vartotojas500** [comment]
No, @Ash-Bash . I have only one sticker and I cant save more. Somehow, the program doesn't allow me to even delete it. Sometimes I manage to save a new sticker just after I start bot, but it replaces the existing one and at the end I only have one sticker again.
